#!/bin/bash

if [ -z "$1" ]
then
    echo "usage: ./02 user"
    exit
fi
mapfile -t my_array < <( awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd )

function contains() {
    local n=$#
    local value=${!n}
    for ((i=1;i < $#;i++)) {
        if [ "${!i}" == "${value}" ]; then
            echo "y"
            return 0
        fi
    }
    echo "n"
    return 1
}

if [ $(contains "${my_array[@]}" $1) == "n" ]; then
    echo "Not a valid user."
    exit
fi

sudo pkill -u $1 && sudo userdel -rf $1

echo "User processes killed and user deleted."




